{
 "title": "Kubernetes - Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up,cluster)" } }
  ]
 },
 "panels": [
  { "title": "K8S Nodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"})",
     "legendFormat": "pods count"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=\"$cluster\",resource=\"pods\", unit=\"integer\"})",
     "legendFormat": "pods limit"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=\"$cluster\",resource=\"pods\", unit=\"integer\"})by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"}) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\",resource=\"pods\", unit=\"integer\"})by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=\"$cluster\"}[$__rate_interval])) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\",unit=\"core\",resource=\"cpu\"})by (node)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\"}) by (node) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", cluster=\"$cluster\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", cluster=\"$cluster\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\"})-sum(node_filesystem_avail_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1-sum(node_filesystem_avail_bytes{cluster=\"$cluster\"})/sum(node_filesystem_size_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=\"$cluster\"}[$__rate_interval])) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\",unit=\"core\",resource=\"cpu\"})by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", cluster=\"$cluster\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=\"$cluster\",resource=\"pods\", unit=\"integer\"})by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"}) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\",resource=\"pods\", unit=\"integer\"})by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=\"$cluster\"}[$__rate_interval])) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\",unit=\"core\",resource=\"cpu\"})by (node)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\"}) by (node) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", cluster=\"$cluster\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", cluster=\"$cluster\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\"})-sum(node_filesystem_avail_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1-sum(node_filesystem_avail_bytes{cluster=\"$cluster\"})/sum(node_filesystem_size_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{cluster=\"$cluster\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} in"
    },
    {
     "expr": "-sum (irate(container_network_transmit_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))by (node)",
     "legendFormat": "{{node}} out"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(sum(node_filesystem_avail_bytes{cluster=\"$cluster\"}) by (instance) / sum(node_filesystem_size_bytes{cluster=\"$cluster\"}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}